### ISSUE TITLE
Display not extending to full size on Vita

### ISSUE THREAD

**Issue by DRok17** [Calistex/fanwor-vita#1]
Compiled the source and the display appears to "letterbox" and not go fullscreen. Seems the resolution matches the game over PNG at 512 by 384.

![2021-05-25-000119-987968](https://user-images.githubusercontent.com/81541725/119438713-ca778180-bcee-11eb-8756-465d59d2ba7e.png)

**Comment by Calistex** [comment]
Indeed, I thought that changing the res from [this line](https://github.com/Calistex/fanwor-vita/blob/64ace68493c8c0dcd2aa982b8da3c1bb00fb85bd/src/arch/sdl/fwguiini.c#L54) to match the Vita one would scale everything up, but it seems it's not enough, it just moves the game frame to the top left. 

Changing the size of the images actually makes them fill the screen, but the game window must have hardcoded sizes.

**Comment by DRok17** [comment]
Oh ok. no worries. Might as well close I guess. Thanks!
